#!/bin/bash
# Version: 24 (Modular)

DIR=$(dirname $(readlink -f "$0"))

# Используем единый скрипт для получения данных
plasmoidName=$("$DIR/get_metadata.sh" "Id")
widgetName="${plasmoidName##*.}"
bugAddress=$("$DIR/get_metadata.sh" "Website")

packageRoot=".." 
projectName="plasma_applet_${plasmoidName}"

if [ -z "$plasmoidName" ]; then
	echo "[merge] Error: Couldn't read 'Id' from metadata.json."
	exit 1
fi

if [ -z "$(which xgettext)" ]; then
	echo "[merge] Error: xgettext command not found."
	echo "[merge] Running 'sudo apt install gettext'"
	sudo apt install gettext
fi

echo "[merge] Extracting messages"
potArgs="--from-code=UTF-8 --width=200 --add-location=file"

find "${packageRoot}" -name '*.cpp' -o -name '*.h' -o -name '*.c' -o -name '*.qml' -o -name '*.js' | \
sort > "${DIR}/infiles.list"

xgettext \
	${potArgs} \
	--files-from="${DIR}/infiles.list" \
	-C -kde \
	-ci18n \
	-ki18n:1 -ki18nc:1c,2 -ki18np:1,2 -ki18ncp:1c,2,3 \
	-kki18n:1 -kki18nc:1c,2 -kki18np:1,2 -kki18ncp:1c,2,3 \
	-kxi18n:1 -kxi18nc:1c,2 -kxi18np:1,2 -kxi18ncp:1c,2,3 \
	-kkxi18n:1 -kkxi18nc:1c,2 -kkxi18np:1,2 -kkxi18ncp:1c,2,3 \
	-kI18N_NOOP:1 -kI18NC_NOOP:1c,2 \
	-kI18N_NOOP2:1c,2 -kI18N_NOOP2_NOSTRIP:1c,2 \
	-ktr2i18n:1 -ktr2xi18n:1 \
	-kN_:1 \
	-kaliasLocale \
	--package-name="${widgetName}" \
	--msgid-bugs-address="${bugAddress}" \
	-D "${packageRoot}" \
	-D "${DIR}" \
	-o "template.pot.new"

if [ $? -ne 0 ]; then
	echo "[merge] error while calling xgettext. aborting."
	exit 1
fi

sed -i 's/# SOME DESCRIPTIVE TITLE./'"# Translation of ${widgetName} in LANGUAGE"'/' "template.pot.new"
sed -i 's/# Copyright (C) YEAR THE PACKAGE'"'"'S COPYRIGHT HOLDER/'"# Copyright (C) $(date +%Y)"'/' "template.pot.new"

if [ -f "template.pot" ]; then
	newPotDate=$(grep "POT-Creation-Date:" template.pot.new | sed 's/.\{3\}$//')
	oldPotDate=$(grep "POT-Creation-Date:" template.pot | sed 's/.\{3\}$//')
	sed -i 's/'"${newPotDate}"'/'"${oldPotDate}"'/' "template.pot.new"
	changes=$(diff "template.pot" "template.pot.new")
	if [ ! -z "$changes" ]; then
		sed -i 's/'"${oldPotDate}"'/'"${newPotDate}"'/' "template.pot.new"
		mv "template.pot.new" "template.pot"
		echo "Template updated."
	else
		rm "template.pot.new"
		echo "No changes in template."
	fi
else
	mv "template.pot.new" "template.pot"
fi

rm "${DIR}/infiles.list"
echo "[merge] Done extracting messages"

echo "[merge] Merging messages"
catalogs=$(find . -name '*.po' | sort)
for cat in $catalogs; do
	echo "[merge] $cat"
	catLocale=$(basename "${cat%.*}")
    
	cp "$cat" "$cat.new"
	sed -i 's/"Content-Type: text\/plain; charset=CHARSET\\n"/"Content-Type: text\/plain; charset=UTF-8\\n"/' "$cat.new"

	msgmerge \
		--width=400 \
		--add-location=file \
		--no-fuzzy-matching \
		-o "$cat.new" \
		"$cat.new" "${DIR}/template.pot"

	sed -i 's/# SOME DESCRIPTIVE TITLE./'"# Translation of ${widgetName} in ${catLocale}"'/' "$cat.new"
	mv "$cat.new" "$cat"
done
echo "[merge] Done merging messages"
